export interface Product {
  id: string;
  name: string;
  collection: string;
  price: number;
  description: string;
  image: string;
  category: "floral" | "woody" | "oriental" | "fresh";
  notes: string[];
}

export const products: Product[] = [
  {
    id: "1",
    name: "Noir Absolute",
    collection: "Midnight Series",
    price: 5500,
    description: "A deep, mysterious blend of black orchid, dark chocolate, and spicy incense.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Black Orchid", "Truffle", "Incense"],
  },
  {
    id: "2",
    name: "Blanc de Blanc",
    collection: "Pure Essence",
    price: 5500,
    description: "Crisp white linen, morning dew, and a hint of white jasmine.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop",
    category: "floral",
    notes: ["Jasmin", "Cotton", "White Musk"],
  },
  {
    id: "3",
    name: "Oud Royale",
    collection: "Legacy Collection",
    price: 5500,
    description: "A majestic oriental composition with rare agarwood, saffron, and aged leather.",
    image: "https://images.unsplash.com/photo-1583445013765-48c2200171a1?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Agarwood", "Saffron", "Leather"],
  },
  {
    id: "4",
    name: "Mystic Fig",
    collection: "Botanical Garden",
    price: 5500,
    description: "Earthyt Mediterranean fig leaves, cedarwood, and a touch of wild honey.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1000&auto=format&fit=crop",
    category: "fresh",
    notes: ["Fig Leaf", "Cedar", "Honey"],
  },
  {
    id: "5",
    name: "Santal 33 Alternative",
    collection: "Icons",
    price: 5500,
    description: "The iconic scent of the American West: cardamom, iris, violet, and ambrox.",
    image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Sandalwood", "Cardamom", "Violet"],
  },
  {
    id: "6",
    name: "Rose Éternelle",
    collection: "Floral Archive",
    price: 5500,
    description: "Damask rose petals crushed with pink pepper and a base of rich amber.",
    image: "https://images.unsplash.com/photo-1616948055599-921868478f7e?q=80&w=1000&auto=format&fit=crop",
    category: "floral",
    notes: ["Damask Rose", "Pink Pepper", "Amber"],
  },
  {
    id: "7",
    name: "Lunar Cedar",
    collection: "Midnight Series",
    price: 5500,
    description: "Silver cedar, cold moonstone accord, and ethereal white musk.",
    image: "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Cedar", "Moonstone", "White Musk"],
  },
  {
    id: "8",
    name: "Golden Saffron",
    collection: "Legacy Collection",
    price: 5500,
    description: "The world's most expensive spice met with honey and aged tobacco.",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Saffron", "Honey", "Tobacco"],
  },
  {
    id: "9",
    name: "Citrus Lab",
    collection: "Botanical Garden",
    price: 5500,
    description: "Zesty bergamot, green tea, and crushed mint leaves.",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d82666?q=80&w=1000&auto=format&fit=crop",
    category: "fresh",
    notes: ["Bergamot", "Green Tea", "Mint"],
  },
  {
    id: "10",
    name: "Velvet Iris",
    collection: "Pure Essence",
    price: 5500,
    description: "Powdery iris root, italian bergamot, and a base of creamy sandalwood.",
    image: "https://images.unsplash.com/photo-1615484476889-7027b1652136?q=80&w=1000&auto=format&fit=crop",
    category: "floral",
    notes: ["Iris", "Bergamot", "Sandalwood"],
  },
  {
    id: "11",
    name: "Amber Smoke",
    collection: "Midnight Series",
    price: 5500,
    description: "Burning amber resin, birch tar, and sweet vanilla bean.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Amber", "Birch Tar", "Vanilla"],
  },
  {
    id: "12",
    name: "Emerald Forest",
    collection: "Botanical Garden",
    price: 5500,
    description: "Pine needles, damp earth, and moss-covered stones.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Pine", "Moss", "Earth"],
  },
  {
    id: "13",
    name: "Dior Sauvage",
    collection: "Christian Dior",
    price: 5500,
    description: "A radically fresh composition, dictated by a name that has the ring of a manifesto.",
    image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Bergamot", "Ambrixan", "Pepper"],
  },
  {
    id: "14",
    name: "Dior J'adore",
    collection: "Christian Dior",
    price: 5500,
    description: "An iconic fragrance, J'adore Eau de Parfum is the grand feminine floral by the House of Dior.",
    image: "https://images.unsplash.com/photo-1585120040315-2241b774ad0f?q=80&w=1000&auto=format&fit=crop",
    category: "floral",
    notes: ["Ylang-ylang", "Damascus Rose", "Jasmine"],
  },
  {
    id: "15",
    name: "Dior Fahrenheit",
    collection: "Christian Dior",
    price: 5500,
    description: "Creativity, distinction and character: the Fahrenheit signature is unique.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Leather", "Violet", "Mandarin"],
  },
  {
    id: "16",
    name: "Dior Homme Intense",
    collection: "Christian Dior",
    price: 5500,
    description: "The ultimate nobility and sophistication of a generous and powerful Eau de Parfum.",
    image: "https://images.unsplash.com/photo-161548447778-ca3b77940c25?q=80&w=1000&auto=format&fit=crop",
    category: "woody",
    notes: ["Iris", "Ambrette", "Cedar"],
  },
  {
    id: "17",
    name: "Dior Poison Girl",
    collection: "Christian Dior",
    price: 5500,
    description: "The fragrance of a modern-day girl, free and sexy.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Bitter Orange", "Rose", "Tonka Bean"],
  },
  {
    id: "18",
    name: "JPG Le Male",
    collection: "Jean Paul Gaultier",
    price: 5500,
    description: "The sailor's fragrance: as virile as it is sexy.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Mint", "Lavender", "Vanilla"],
  },
  {
    id: "19",
    name: "JPG Classique",
    collection: "Jean Paul Gaultier",
    price: 5500,
    description: "A symbol of seduction and extreme sensuality.",
    image: "https://images.unsplash.com/photo-1583445013765-48c2200171a1?q=80&w=1000&auto=format&fit=crop",
    category: "floral",
    notes: ["Orange Blossom", "Ginger", "Vanilla"],
  },
  {
    id: "20",
    name: "JPG Scandal",
    collection: "Jean Paul Gaultier",
    price: 5500,
    description: "The fragrance for a woman who is free and strong.",
    image: "https://images.unsplash.com/photo-1616948055599-921868478f7e?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Honey", "Gardenia", "Patchouli"],
  },
  {
    id: "21",
    name: "JPG Ultra Male",
    collection: "Jean Paul Gaultier",
    price: 5500,
    description: "The rogue sailor who will have you lost at sea!",
    image: "https://images.unsplash.com/photo-1615484476889-7027b1652136?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Pear", "Black Lavender", "Vanilla"],
  },
  {
    id: "22",
    name: "JPG Le Male Elixir",
    collection: "Jean Paul Gaultier",
    price: 5500,
    description: "A woody aromatic amber fragrance that sets the senses on fire.",
    image: "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?q=80&w=1000&auto=format&fit=crop",
    category: "oriental",
    notes: ["Lavender", "Benzoin", "Tonka Bean"],
  },
];
